[project]
name = "pdf-agent-rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "langchain-classic>=1.0.8",
    "langchain-huggingface>=1.2.2",
    "langchain-openai>=1.6.0",
    "langchain-pinecone>=0.2.13",
    "fastapi>=0.139.0",
    "pydantic>=2.13.4",
    "pydantic-settings>=2.14.2",
    "sentence-transformers>=6.0.0",
    "uvicorn[standard]>=0.50.2",
]

[dependency-groups]
dev = [
    "httpx>=0.28.1",
    "ipykernel>=7.3.0",
    "ipython>=9.15.0",
    "ipywidgets>=8.1.8",
    "jupyter>=1.1.1",
    "langchain-community>=0.4.2",
    "langchain-text-splitters>=1.1.2",
    "matplotlib>=3.11.0",
    "pandas>=3.0.3",
    "plotly>=6.8.0",
    "pytest>=9.1.1",
    "seaborn>=0.13.2",
    "streamlit>=1.61.1",
]

[tool.uv.workspace]
members = [
    "AI",
]
